name: tauon
version: "3.3.0"
summary: Graphical SFTP client and terminal emulator with helpful utilities
description: |
  Tauon is a graphical SSH client. It has a file browser,
  terminal emulator, resource/process manager, disk space analyzer, 
  text editor, log viewer and lots of other helpful tools, 
  which makes it easy to work with remote servers.

  More information is available on GitHub Repo: https://github.com/achiikun/muon-ssh
grade: stable
base: core18
icon: snap/gui/tauonssh.png
confinement: strict

apps:
  tauon:
    command: java -jar $SNAP/jar/tauonssh_3.3.0.jar
    common-id: tauonssh.desktop
    environment:
      # Needed for fontconfig
      XDG_DATA_HOME: ${SNAP}/usr/share
      FONTCONFIG_PATH: ${SNAP}/etc/fonts/config.d
      FONTCONFIG_FILE: ${SNAP}/etc/fonts/fonts.conf
    plugs: [x11, ssh-keys, network, desktop, home, network-bind]

parts:
  tauon:
    plugin: maven
    source: .
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/jar/
      snapcraftctl build
      cp ./tauon-app/target/*.jar $SNAPCRAFT_PART_INSTALL/jar/
      cp ./tauon-jediterm/target/*.jar $SNAPCRAFT_PART_INSTALL/jar/
    maven-targets:
      - /root/parts/tauon/build/tauon-app
      - /root/parts/tauon/build/tauon-jediterm
    build-packages:
      - openjdk-11-jdk
    stage-packages:
      - openjdk-11-jre
      - x11-utils
